### ISSUE TITLE
Freezing generator layers

### ISSUE THREAD

**Issue by slala2121** [MiaoyunZhao/GANTransferLimitedData#4]
Hi, I'm curious why toggle_grad_G has been commented out; it seems like this would need to be used to transfer and freeze the relevant subset of layers as in the paper? Otherwise the current code seems to be transferring and freezing all the layers?

**Comment by MiaoyunZhao** [comment]
> Hi, I'm curious why toggle_grad_G has been commented out; it seems like this would need to be used to transfer and freeze the relevant subset of layers as in the paper? Otherwise the current code seems to be transferring and freezing all the layers?

For our method, the layers transferred are freeze all the time, only the introduced smallhead and the gamma/beta in AdaFM are trainable. So, we don't need  "toggle_grad_G" anymore. Hope it helps~

**Comment by slala2121** [comment]
Thanks for your reply. Right, I understand that. But in the paper, only the 4 top layers of the generator were transferred and freezed instead of the entire generator. I thought setting the parameter in the config i.e., config['generator']['glayers']=-4 would take care of this. But I don't see this ever used in the code, so it seems like **all** the layers of the generator are being transferred instead of the 4 top layers.

**Comment by MiaoyunZhao** [comment]
The setting config['generator']['glayers']=-4 is useless in our method, because our model is defined as in figure1(h), only the last four layers will be transferred ( just like what shows in the code), the other layers will be omitted automatically .

**Comment by MiaoyunZhao** [comment]
> Thanks for your reply. Right, I understand that. But in the paper, only the 4 top layers of the generator were transferred and freezed instead of the entire generator. I thought setting the parameter in the config i.e., config['generator']['glayers']=-4 would take care of this. But I don't see this ever used in the code, so it seems like **all** the layers of the generator are being transferred instead of the 4 top layers.

The setting config['generator']['glayers']=-4 is useless in our method, because our model is defined as in figure1(h), only the last four layers will be transferred ( just like what shows in the code), the other layers will be omitted automatically, please refer to the function 'model_equal_part(model, dict_all)'.

**Comment by slala2121** [comment]
Thanks, I see now. Although the dictionary of weights is the full imagenet pretrained model, the resnet2_AdaFM Generator class specifies that only the the 4 layers of the pretrained generator be transferred.
